// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/trace_packet_defaults.proto
// Protobuf Java Version: 4.29.3

package org.eclipse.tracecompass.incubator.internal.perfetto.protos;

public final class TracePacketDefaultsOuterClass {
  private TracePacketDefaultsOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      TracePacketDefaultsOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TracePacketDefaultsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.TracePacketDefaults)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 timestamp_clock_id = 58;</code>
     * @return Whether the timestampClockId field is set.
     */
    boolean hasTimestampClockId();
    /**
     * <code>optional uint32 timestamp_clock_id = 58;</code>
     * @return The timestampClockId.
     */
    int getTimestampClockId();

    /**
     * <pre>
     * Default values for TrackEvents (e.g. default track).
     * </pre>
     *
     * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
     * @return Whether the trackEventDefaults field is set.
     */
    boolean hasTrackEventDefaults();
    /**
     * <pre>
     * Default values for TrackEvents (e.g. default track).
     * </pre>
     *
     * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
     * @return The trackEventDefaults.
     */
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults getTrackEventDefaults();
    /**
     * <pre>
     * Default values for TrackEvents (e.g. default track).
     * </pre>
     *
     * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
     */
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaultsOrBuilder getTrackEventDefaultsOrBuilder();

    /**
     * <pre>
     * Defaults for perf profiler packets (PerfSample).
     * </pre>
     *
     * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
     * @return Whether the perfSampleDefaults field is set.
     */
    boolean hasPerfSampleDefaults();
    /**
     * <pre>
     * Defaults for perf profiler packets (PerfSample).
     * </pre>
     *
     * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
     * @return The perfSampleDefaults.
     */
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults getPerfSampleDefaults();
    /**
     * <pre>
     * Defaults for perf profiler packets (PerfSample).
     * </pre>
     *
     * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
     */
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaultsOrBuilder getPerfSampleDefaultsOrBuilder();
  }
  /**
   * <pre>
   * Default values for TracePacket fields that hold for a particular TraceWriter
   * packet sequence. This message contains a subset of the TracePacket fields
   * with matching IDs. When provided, these fields define the default values
   * that should be applied, at import time, to all TracePacket(s) with the same
   * |trusted_packet_sequence_id|, unless otherwise specified in each packet.
   *
   * Should be reemitted whenever incremental state is cleared on the sequence.
   * </pre>
   *
   * Protobuf type {@code perfetto.protos.TracePacketDefaults}
   */
  public static final class TracePacketDefaults extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.TracePacketDefaults)
      TracePacketDefaultsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        TracePacketDefaults.class.getName());
    }
    // Use TracePacketDefaults.newBuilder() to construct.
    private TracePacketDefaults(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TracePacketDefaults() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.internal_static_perfetto_protos_TracePacketDefaults_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.internal_static_perfetto_protos_TracePacketDefaults_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults.class, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults.Builder.class);
    }

    private int bitField0_;
    public static final int TIMESTAMP_CLOCK_ID_FIELD_NUMBER = 58;
    private int timestampClockId_ = 0;
    /**
     * <code>optional uint32 timestamp_clock_id = 58;</code>
     * @return Whether the timestampClockId field is set.
     */
    @java.lang.Override
    public boolean hasTimestampClockId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 timestamp_clock_id = 58;</code>
     * @return The timestampClockId.
     */
    @java.lang.Override
    public int getTimestampClockId() {
      return timestampClockId_;
    }

    public static final int TRACK_EVENT_DEFAULTS_FIELD_NUMBER = 11;
    private org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults trackEventDefaults_;
    /**
     * <pre>
     * Default values for TrackEvents (e.g. default track).
     * </pre>
     *
     * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
     * @return Whether the trackEventDefaults field is set.
     */
    @java.lang.Override
    public boolean hasTrackEventDefaults() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Default values for TrackEvents (e.g. default track).
     * </pre>
     *
     * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
     * @return The trackEventDefaults.
     */
    @java.lang.Override
    public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults getTrackEventDefaults() {
      return trackEventDefaults_ == null ? org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.getDefaultInstance() : trackEventDefaults_;
    }
    /**
     * <pre>
     * Default values for TrackEvents (e.g. default track).
     * </pre>
     *
     * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
     */
    @java.lang.Override
    public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaultsOrBuilder getTrackEventDefaultsOrBuilder() {
      return trackEventDefaults_ == null ? org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.getDefaultInstance() : trackEventDefaults_;
    }

    public static final int PERF_SAMPLE_DEFAULTS_FIELD_NUMBER = 12;
    private org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults perfSampleDefaults_;
    /**
     * <pre>
     * Defaults for perf profiler packets (PerfSample).
     * </pre>
     *
     * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
     * @return Whether the perfSampleDefaults field is set.
     */
    @java.lang.Override
    public boolean hasPerfSampleDefaults() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Defaults for perf profiler packets (PerfSample).
     * </pre>
     *
     * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
     * @return The perfSampleDefaults.
     */
    @java.lang.Override
    public org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults getPerfSampleDefaults() {
      return perfSampleDefaults_ == null ? org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.getDefaultInstance() : perfSampleDefaults_;
    }
    /**
     * <pre>
     * Defaults for perf profiler packets (PerfSample).
     * </pre>
     *
     * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
     */
    @java.lang.Override
    public org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaultsOrBuilder getPerfSampleDefaultsOrBuilder() {
      return perfSampleDefaults_ == null ? org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.getDefaultInstance() : perfSampleDefaults_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(11, getTrackEventDefaults());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(12, getPerfSampleDefaults());
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(58, timestampClockId_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getTrackEventDefaults());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getPerfSampleDefaults());
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(58, timestampClockId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults)) {
        return super.equals(obj);
      }
      org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults other = (org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults) obj;

      if (hasTimestampClockId() != other.hasTimestampClockId()) return false;
      if (hasTimestampClockId()) {
        if (getTimestampClockId()
            != other.getTimestampClockId()) return false;
      }
      if (hasTrackEventDefaults() != other.hasTrackEventDefaults()) return false;
      if (hasTrackEventDefaults()) {
        if (!getTrackEventDefaults()
            .equals(other.getTrackEventDefaults())) return false;
      }
      if (hasPerfSampleDefaults() != other.hasPerfSampleDefaults()) return false;
      if (hasPerfSampleDefaults()) {
        if (!getPerfSampleDefaults()
            .equals(other.getPerfSampleDefaults())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTimestampClockId()) {
        hash = (37 * hash) + TIMESTAMP_CLOCK_ID_FIELD_NUMBER;
        hash = (53 * hash) + getTimestampClockId();
      }
      if (hasTrackEventDefaults()) {
        hash = (37 * hash) + TRACK_EVENT_DEFAULTS_FIELD_NUMBER;
        hash = (53 * hash) + getTrackEventDefaults().hashCode();
      }
      if (hasPerfSampleDefaults()) {
        hash = (37 * hash) + PERF_SAMPLE_DEFAULTS_FIELD_NUMBER;
        hash = (53 * hash) + getPerfSampleDefaults().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Default values for TracePacket fields that hold for a particular TraceWriter
     * packet sequence. This message contains a subset of the TracePacket fields
     * with matching IDs. When provided, these fields define the default values
     * that should be applied, at import time, to all TracePacket(s) with the same
     * |trusted_packet_sequence_id|, unless otherwise specified in each packet.
     *
     * Should be reemitted whenever incremental state is cleared on the sequence.
     * </pre>
     *
     * Protobuf type {@code perfetto.protos.TracePacketDefaults}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.TracePacketDefaults)
        org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaultsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.internal_static_perfetto_protos_TracePacketDefaults_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.internal_static_perfetto_protos_TracePacketDefaults_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults.class, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults.Builder.class);
      }

      // Construct using perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getTrackEventDefaultsFieldBuilder();
          getPerfSampleDefaultsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestampClockId_ = 0;
        trackEventDefaults_ = null;
        if (trackEventDefaultsBuilder_ != null) {
          trackEventDefaultsBuilder_.dispose();
          trackEventDefaultsBuilder_ = null;
        }
        perfSampleDefaults_ = null;
        if (perfSampleDefaultsBuilder_ != null) {
          perfSampleDefaultsBuilder_.dispose();
          perfSampleDefaultsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.internal_static_perfetto_protos_TracePacketDefaults_descriptor;
      }

      @java.lang.Override
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults getDefaultInstanceForType() {
        return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults.getDefaultInstance();
      }

      @java.lang.Override
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults build() {
        org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults buildPartial() {
        org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults result = new org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestampClockId_ = timestampClockId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.trackEventDefaults_ = trackEventDefaultsBuilder_ == null
              ? trackEventDefaults_
              : trackEventDefaultsBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.perfSampleDefaults_ = perfSampleDefaultsBuilder_ == null
              ? perfSampleDefaults_
              : perfSampleDefaultsBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults) {
          return mergeFrom((org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults other) {
        if (other == org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults.getDefaultInstance()) return this;
        if (other.hasTimestampClockId()) {
          setTimestampClockId(other.getTimestampClockId());
        }
        if (other.hasTrackEventDefaults()) {
          mergeTrackEventDefaults(other.getTrackEventDefaults());
        }
        if (other.hasPerfSampleDefaults()) {
          mergePerfSampleDefaults(other.getPerfSampleDefaults());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 90: {
                input.readMessage(
                    getTrackEventDefaultsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 90
              case 98: {
                input.readMessage(
                    getPerfSampleDefaultsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 98
              case 464: {
                timestampClockId_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 464
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int timestampClockId_ ;
      /**
       * <code>optional uint32 timestamp_clock_id = 58;</code>
       * @return Whether the timestampClockId field is set.
       */
      @java.lang.Override
      public boolean hasTimestampClockId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 timestamp_clock_id = 58;</code>
       * @return The timestampClockId.
       */
      @java.lang.Override
      public int getTimestampClockId() {
        return timestampClockId_;
      }
      /**
       * <code>optional uint32 timestamp_clock_id = 58;</code>
       * @param value The timestampClockId to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampClockId(int value) {

        timestampClockId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 timestamp_clock_id = 58;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestampClockId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestampClockId_ = 0;
        onChanged();
        return this;
      }

      private org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults trackEventDefaults_;
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaultsOrBuilder> trackEventDefaultsBuilder_;
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       * @return Whether the trackEventDefaults field is set.
       */
      public boolean hasTrackEventDefaults() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       * @return The trackEventDefaults.
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults getTrackEventDefaults() {
        if (trackEventDefaultsBuilder_ == null) {
          return trackEventDefaults_ == null ? org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.getDefaultInstance() : trackEventDefaults_;
        } else {
          return trackEventDefaultsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       */
      public Builder setTrackEventDefaults(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults value) {
        if (trackEventDefaultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trackEventDefaults_ = value;
        } else {
          trackEventDefaultsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       */
      public Builder setTrackEventDefaults(
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.Builder builderForValue) {
        if (trackEventDefaultsBuilder_ == null) {
          trackEventDefaults_ = builderForValue.build();
        } else {
          trackEventDefaultsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       */
      public Builder mergeTrackEventDefaults(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults value) {
        if (trackEventDefaultsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            trackEventDefaults_ != null &&
            trackEventDefaults_ != org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.getDefaultInstance()) {
            getTrackEventDefaultsBuilder().mergeFrom(value);
          } else {
            trackEventDefaults_ = value;
          }
        } else {
          trackEventDefaultsBuilder_.mergeFrom(value);
        }
        if (trackEventDefaults_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       */
      public Builder clearTrackEventDefaults() {
        bitField0_ = (bitField0_ & ~0x00000002);
        trackEventDefaults_ = null;
        if (trackEventDefaultsBuilder_ != null) {
          trackEventDefaultsBuilder_.dispose();
          trackEventDefaultsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.Builder getTrackEventDefaultsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTrackEventDefaultsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaultsOrBuilder getTrackEventDefaultsOrBuilder() {
        if (trackEventDefaultsBuilder_ != null) {
          return trackEventDefaultsBuilder_.getMessageOrBuilder();
        } else {
          return trackEventDefaults_ == null ?
              org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.getDefaultInstance() : trackEventDefaults_;
        }
      }
      /**
       * <pre>
       * Default values for TrackEvents (e.g. default track).
       * </pre>
       *
       * <code>optional .perfetto.protos.TrackEventDefaults track_event_defaults = 11;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaultsOrBuilder>
          getTrackEventDefaultsFieldBuilder() {
        if (trackEventDefaultsBuilder_ == null) {
          trackEventDefaultsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaults.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.TrackEventDefaultsOrBuilder>(
                  getTrackEventDefaults(),
                  getParentForChildren(),
                  isClean());
          trackEventDefaults_ = null;
        }
        return trackEventDefaultsBuilder_;
      }

      private org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults perfSampleDefaults_;
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults, org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaultsOrBuilder> perfSampleDefaultsBuilder_;
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       * @return Whether the perfSampleDefaults field is set.
       */
      public boolean hasPerfSampleDefaults() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       * @return The perfSampleDefaults.
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults getPerfSampleDefaults() {
        if (perfSampleDefaultsBuilder_ == null) {
          return perfSampleDefaults_ == null ? org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.getDefaultInstance() : perfSampleDefaults_;
        } else {
          return perfSampleDefaultsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       */
      public Builder setPerfSampleDefaults(org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults value) {
        if (perfSampleDefaultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          perfSampleDefaults_ = value;
        } else {
          perfSampleDefaultsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       */
      public Builder setPerfSampleDefaults(
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.Builder builderForValue) {
        if (perfSampleDefaultsBuilder_ == null) {
          perfSampleDefaults_ = builderForValue.build();
        } else {
          perfSampleDefaultsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       */
      public Builder mergePerfSampleDefaults(org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults value) {
        if (perfSampleDefaultsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            perfSampleDefaults_ != null &&
            perfSampleDefaults_ != org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.getDefaultInstance()) {
            getPerfSampleDefaultsBuilder().mergeFrom(value);
          } else {
            perfSampleDefaults_ = value;
          }
        } else {
          perfSampleDefaultsBuilder_.mergeFrom(value);
        }
        if (perfSampleDefaults_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       */
      public Builder clearPerfSampleDefaults() {
        bitField0_ = (bitField0_ & ~0x00000004);
        perfSampleDefaults_ = null;
        if (perfSampleDefaultsBuilder_ != null) {
          perfSampleDefaultsBuilder_.dispose();
          perfSampleDefaultsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.Builder getPerfSampleDefaultsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getPerfSampleDefaultsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaultsOrBuilder getPerfSampleDefaultsOrBuilder() {
        if (perfSampleDefaultsBuilder_ != null) {
          return perfSampleDefaultsBuilder_.getMessageOrBuilder();
        } else {
          return perfSampleDefaults_ == null ?
              org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.getDefaultInstance() : perfSampleDefaults_;
        }
      }
      /**
       * <pre>
       * Defaults for perf profiler packets (PerfSample).
       * </pre>
       *
       * <code>optional .perfetto.protos.PerfSampleDefaults perf_sample_defaults = 12;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults, org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaultsOrBuilder>
          getPerfSampleDefaultsFieldBuilder() {
        if (perfSampleDefaultsBuilder_ == null) {
          perfSampleDefaultsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults, org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaults.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.PerfSampleDefaultsOrBuilder>(
                  getPerfSampleDefaults(),
                  getParentForChildren(),
                  isClean());
          perfSampleDefaults_ = null;
        }
        return perfSampleDefaultsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:perfetto.protos.TracePacketDefaults)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.TracePacketDefaults)
    private static final org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults();
    }

    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TracePacketDefaults>
        PARSER = new com.google.protobuf.AbstractParser<TracePacketDefaults>() {
      @java.lang.Override
      public TracePacketDefaults parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TracePacketDefaults> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TracePacketDefaults> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketDefaultsOuterClass.TracePacketDefaults getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_TracePacketDefaults_descriptor;
  private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_perfetto_protos_TracePacketDefaults_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1protos/perfetto/trace/trace_packet_def" +
      "aults.proto\022\017perfetto.protos\0324protos/per" +
      "fetto/trace/profiling/profile_packet.pro" +
      "to\0323protos/perfetto/trace/track_event/tr" +
      "ack_event.proto\"\267\001\n\023TracePacketDefaults\022" +
      "\032\n\022timestamp_clock_id\030: \001(\r\022A\n\024track_eve" +
      "nt_defaults\030\013 \001(\0132#.perfetto.protos.Trac" +
      "kEventDefaults\022A\n\024perf_sample_defaults\030\014" +
      " \001(\0132#.perfetto.protos.PerfSampleDefault" +
      "s"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.getDescriptor(),
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.getDescriptor(),
        });
    internal_static_perfetto_protos_TracePacketDefaults_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfetto_protos_TracePacketDefaults_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_perfetto_protos_TracePacketDefaults_descriptor,
        new java.lang.String[] { "TimestampClockId", "TrackEventDefaults", "PerfSampleDefaults", });
    descriptor.resolveAllFeaturesImmutable();
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.ProfilePacketOuterClass.getDescriptor();
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.TrackEventOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
