// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protos/perfetto/trace/trace.proto
// Protobuf Java Version: 4.29.3

package org.eclipse.tracecompass.incubator.internal.perfetto.protos;

public final class TraceOuterClass {
  private TraceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      TraceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TraceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:perfetto.protos.Trace)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    java.util.List<org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket>
        getPacketList();
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket getPacket(int index);
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    int getPacketCount();
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    java.util.List<? extends org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder>
        getPacketOrBuilderList();
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder getPacketOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code perfetto.protos.Trace}
   */
  public static final class Trace extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:perfetto.protos.Trace)
      TraceOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        Trace.class.getName());
    }
    // Use Trace.newBuilder() to construct.
    private Trace(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Trace() {
      packet_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.internal_static_perfetto_protos_Trace_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.internal_static_perfetto_protos_Trace_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace.class, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace.Builder.class);
    }

    public static final int PACKET_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket> packet_;
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket> getPacketList() {
      return packet_;
    }
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder>
        getPacketOrBuilderList() {
      return packet_;
    }
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    @java.lang.Override
    public int getPacketCount() {
      return packet_.size();
    }
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    @java.lang.Override
    public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket getPacket(int index) {
      return packet_.get(index);
    }
    /**
     * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
     */
    @java.lang.Override
    public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder getPacketOrBuilder(
        int index) {
      return packet_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPacketCount(); i++) {
        if (!getPacket(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < packet_.size(); i++) {
        output.writeMessage(1, packet_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < packet_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, packet_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace)) {
        return super.equals(obj);
      }
      org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace other = (org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace) obj;

      if (!getPacketList()
          .equals(other.getPacketList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPacketCount() > 0) {
        hash = (37 * hash) + PACKET_FIELD_NUMBER;
        hash = (53 * hash) + getPacketList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code perfetto.protos.Trace}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:perfetto.protos.Trace)
        org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.TraceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.internal_static_perfetto_protos_Trace_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.internal_static_perfetto_protos_Trace_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace.class, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace.Builder.class);
      }

      // Construct using perfetto.protos.TraceOuterClass.Trace.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (packetBuilder_ == null) {
          packet_ = java.util.Collections.emptyList();
        } else {
          packet_ = null;
          packetBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.internal_static_perfetto_protos_Trace_descriptor;
      }

      @java.lang.Override
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace getDefaultInstanceForType() {
        return org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace.getDefaultInstance();
      }

      @java.lang.Override
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace build() {
        org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace buildPartial() {
        org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace result = new org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace result) {
        if (packetBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            packet_ = java.util.Collections.unmodifiableList(packet_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.packet_ = packet_;
        } else {
          result.packet_ = packetBuilder_.build();
        }
      }

      private void buildPartial0(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace) {
          return mergeFrom((org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace other) {
        if (other == org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace.getDefaultInstance()) return this;
        if (packetBuilder_ == null) {
          if (!other.packet_.isEmpty()) {
            if (packet_.isEmpty()) {
              packet_ = other.packet_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePacketIsMutable();
              packet_.addAll(other.packet_);
            }
            onChanged();
          }
        } else {
          if (!other.packet_.isEmpty()) {
            if (packetBuilder_.isEmpty()) {
              packetBuilder_.dispose();
              packetBuilder_ = null;
              packet_ = other.packet_;
              bitField0_ = (bitField0_ & ~0x00000001);
              packetBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPacketFieldBuilder() : null;
            } else {
              packetBuilder_.addAllMessages(other.packet_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getPacketCount(); i++) {
          if (!getPacket(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket m =
                    input.readMessage(
                        org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.parser(),
                        extensionRegistry);
                if (packetBuilder_ == null) {
                  ensurePacketIsMutable();
                  packet_.add(m);
                } else {
                  packetBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket> packet_ =
        java.util.Collections.emptyList();
      private void ensurePacketIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          packet_ = new java.util.ArrayList<org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket>(packet_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder> packetBuilder_;

      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public java.util.List<org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket> getPacketList() {
        if (packetBuilder_ == null) {
          return java.util.Collections.unmodifiableList(packet_);
        } else {
          return packetBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public int getPacketCount() {
        if (packetBuilder_ == null) {
          return packet_.size();
        } else {
          return packetBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket getPacket(int index) {
        if (packetBuilder_ == null) {
          return packet_.get(index);
        } else {
          return packetBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder setPacket(
          int index, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket value) {
        if (packetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketIsMutable();
          packet_.set(index, value);
          onChanged();
        } else {
          packetBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder setPacket(
          int index, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder builderForValue) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          packet_.set(index, builderForValue.build());
          onChanged();
        } else {
          packetBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder addPacket(org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket value) {
        if (packetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketIsMutable();
          packet_.add(value);
          onChanged();
        } else {
          packetBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder addPacket(
          int index, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket value) {
        if (packetBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePacketIsMutable();
          packet_.add(index, value);
          onChanged();
        } else {
          packetBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder addPacket(
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder builderForValue) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          packet_.add(builderForValue.build());
          onChanged();
        } else {
          packetBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder addPacket(
          int index, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder builderForValue) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          packet_.add(index, builderForValue.build());
          onChanged();
        } else {
          packetBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder addAllPacket(
          java.lang.Iterable<? extends org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket> values) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, packet_);
          onChanged();
        } else {
          packetBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder clearPacket() {
        if (packetBuilder_ == null) {
          packet_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          packetBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public Builder removePacket(int index) {
        if (packetBuilder_ == null) {
          ensurePacketIsMutable();
          packet_.remove(index);
          onChanged();
        } else {
          packetBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder getPacketBuilder(
          int index) {
        return getPacketFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder getPacketOrBuilder(
          int index) {
        if (packetBuilder_ == null) {
          return packet_.get(index);  } else {
          return packetBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public java.util.List<? extends org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder>
           getPacketOrBuilderList() {
        if (packetBuilder_ != null) {
          return packetBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(packet_);
        }
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder addPacketBuilder() {
        return getPacketFieldBuilder().addBuilder(
            org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.getDefaultInstance());
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder addPacketBuilder(
          int index) {
        return getPacketFieldBuilder().addBuilder(
            index, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.getDefaultInstance());
      }
      /**
       * <code>repeated .perfetto.protos.TracePacket packet = 1;</code>
       */
      public java.util.List<org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder>
           getPacketBuilderList() {
        return getPacketFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder>
          getPacketFieldBuilder() {
        if (packetBuilder_ == null) {
          packetBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacket.Builder, org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.TracePacketOrBuilder>(
                  packet_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          packet_ = null;
        }
        return packetBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:perfetto.protos.Trace)
    }

    // @@protoc_insertion_point(class_scope:perfetto.protos.Trace)
    private static final org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace();
    }

    public static org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trace>
        PARSER = new com.google.protobuf.AbstractParser<Trace>() {
      @java.lang.Override
      public Trace parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Trace> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trace> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.eclipse.tracecompass.incubator.internal.perfetto.protos.TraceOuterClass.Trace getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_perfetto_protos_Trace_descriptor;
  private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_perfetto_protos_Trace_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!protos/perfetto/trace/trace.proto\022\017per" +
      "fetto.protos\032(protos/perfetto/trace/trac" +
      "e_packet.proto\"5\n\005Trace\022,\n\006packet\030\001 \003(\0132" +
      "\034.perfetto.protos.TracePacket"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.getDescriptor(),
        });
    internal_static_perfetto_protos_Trace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_perfetto_protos_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_perfetto_protos_Trace_descriptor,
        new java.lang.String[] { "Packet", });
    descriptor.resolveAllFeaturesImmutable();
    org.eclipse.tracecompass.incubator.internal.perfetto.protos.TracePacketOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
